sudo: required
language: python
python: "3.8"
dist: focal
env:
  - TOXENV=py38
  - TOXENV=py38-lint
matrix:
  include:
  - python: "3.6"
    env: TOXENV=py36
  - python: "3.7"
    env: TOXENV=py37
before_install:
  - source travisci/sdkman_java_8.sh
install:
  - pip install tox coveralls
script: tox
after_success:
  if [ "$TOXENV" == "py36" ]; then coveralls; fi
